Repository SFDigitalServices/sfgov, pull requests merged in 2021-07, with the labels that each got.

#935 [SG-1412] Add kbd instructions to power bi embeds
  config/sfgov_media.settings.yml
  web/modules/custom/sfgov_media/config/install/sfgov_media.settings.yml
  web/modules/custom/sfgov_media/sfgov_media.links.menu.yml
  web/modules/custom/sfgov_media/sfgov_media.routing.yml
  web/modules/custom/sfgov_media/src/Form/SFGovMediaConfigurationForm.php
  web/themes/custom/sfgovpl/includes/paragraph.inc
  web/themes/custom/sfgovpl/package-lock.json
  web/themes/custom/sfgovpl/package.json
  web/themes/custom/sfgovpl/sfgovpl.libraries.yml
  web/themes/custom/sfgovpl/src/js/powerbi.js
  web/themes/custom/sfgovpl/templates/paragraphs/paragraph--powerbi-embed.html.twig
Labels: c3, ready to merge to develop

#959 [SG-1447] Remove ability to clone transaction nodes.
  config/user.role.digital_services.yml
  config/user.role.writer.yml
Labels: c3, ready to merge to develop

#958 [SG-1311] Fix problem with addresses not getting proper h4 tag
  web/themes/custom/sfgovpl/templates/address/address-plain--location--physical--default-h4.html.twig
  web/themes/custom/sfgovpl/templates/address/address-plain--location--physical.html.twig
Labels: c3, ready to merge to develop

#960 update core to 8.9.17
  composer-manifest.yaml
  composer.lock
Labels: ready to merge to develop

#840 [SG-1298] Create proof of concept for HTML reports.
  composer-manifest.yaml
  composer.json
  composer.lock
  config/block.block.sfgovpl_page_title.yml
  config/core.entity_form_display.node.report.default.yml
  config/core.entity_view_display.node.report.default.yml
  config/core.extension.yml
  config/editor.editor.sf_full_html_with_toc.yml
  config/field.field.node.report.body.yml
  config/field.field.node.report.field_date_only.yml
  config/field.field.node.report.field_description.yml
  config/field.field.node.report.field_spotlight.yml
  config/field.storage.node.field_date_only.yml
  config/filter.format.plain_text.yml
  config/filter.format.sf_full_html_with_toc.yml
  config/language.content_settings.node.report.yml
  config/node.type.report.yml
  config/pathauto.pattern.report.yml
  config/system.action.bulk_update_fields_on_toc_type.yml
  config/toc_api.toc_type.default.yml
  config/toc_api.toc_type.full.yml
  config/toc_api.toc_type.full_numbered.yml
  config/toc_api.toc_type.simple.yml
  config/toc_api.toc_type.simple_numbered.yml
  config/workflows.workflow.editorial.yml
  web/modules/custom/sfgov_doc_html/js/docsearch.js
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.info.yml
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.install
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.libraries.yml
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.links.menu.yml
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.module
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.permissions.yml
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.routing.yml
  web/modules/custom/sfgov_doc_html/sfgov_doc_html.services.yml
  web/modules/custom/sfgov_doc_html/src/Annotation/DocFormatter.php
  web/modules/custom/sfgov_doc_html/src/Element/DocSearch.php
  web/modules/custom/sfgov_doc_html/src/Form/DocUploadForm.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatter/EmptyParagraphs.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatter/RemoveElements.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatter/Style.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatter/Table.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatterBase.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatterInterface.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatterManager.php
  web/modules/custom/sfgov_doc_html/src/Plugin/DocFormatterManagerInterface.php
  web/modules/custom/sfgov_doc_html/src/TableOfContentsBuilder.php
  web/modules/custom/sfgov_doc_html/src/TableOfContentsBuilderInterface.php
  web/modules/custom/sfgov_doc_html/templates/docsearch.html.twig
  web/modules/custom/sfgov_reports/sfgov_reports.info.yml
  web/themes/custom/sfgovpl/includes/page.inc
  web/themes/custom/sfgovpl/includes/toc.inc
  web/themes/custom/sfgovpl/sfgovpl.libraries.yml
  web/themes/custom/sfgovpl/src/img/search-slate-blue.svg
  web/themes/custom/sfgovpl/src/js/toc.js
  web/themes/custom/sfgovpl/src/sass/drupal.css
  web/themes/custom/sfgovpl/src/sass/node/_node-data-story.scss
  web/themes/custom/sfgovpl/src/sass/node/_node-report.scss
  web/themes/custom/sfgovpl/templates/node/node--report--full.html.twig
  web/themes/custom/sfgovpl/templates/paragraphs/paragraph--spotlight.html.twig
  web/themes/custom/sfgovpl/templates/system/toc-tree.html.twig
Labels: c3
